# Travis CI configuration file
# http://travis-ci.org

sudo: false
language: minimal

deploy:
  - provider: script
    script: bash ./.script/deploy_release.sh
    on:
      tags: true
  - provider: script
    script: bash ./.script/deploy_development.sh

notifications:
 email:
  on_success: never
  on_failure: always